<a href="https://colab.research.google.com/github/25wh1a0561-web/NASSCOM/blob/main/week2/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr1 = np.arange(0, 10, 2)
print("Array using arange:", arr1)

Array using arange: [0 2 4 6 8]


In [ ]:
arr2 = np.linspace(0, 1, 5)
print("Array using linspace:", arr2)

Array using linspace: [0.   0.25 0.5  0.75 1.  ]


In [ ]:
arr3 = np.arange(1, 10).reshape((3, 3))
print("Reshaped Array (3x3):\n", arr3)
print("Flattened version:", arr3.flatten())

Reshaped Array (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattened version: [1 2 3 4 5 6 7 8 9]


In [ ]:
data = np.array([[5, 8, 9], [2, 4, 6]])

print("Original Data:\n", data)

Original Data:
 [[5 8 9]
 [2 4 6]]


In [ ]:
print("Sum of all elements:", np.sum(data))
print("Column-wise sum:", np.sum(data, axis=0))
print("Row-wise mean:", np.mean(data, axis=1))
print("Max value:", np.max(data))

Sum of all elements: 34
Column-wise sum: [ 7 12 15]
Row-wise mean: [7.33333333 4.        ]
Max value: 9


In [ ]:
print("Index of max value (flattened):", np.argmax(data))
print("Min value:", np.min(data))
print("Standard Deviation:", np.std(data))

Index of max value (flattened): 2
Min value: 2
Standard Deviation: 2.3570226039551585


In [ ]:
a = np.array([3, 1, 7, 2, 9])
print("Original Array:", a)

Original Array: [3 1 7 2 9]


In [ ]:
sorted_array = np.sort(a)
print("Sorted Array:", sorted_array)
idx = np.where(a > 4)
print("Indices where value > 4:", idx)
print("Values > 4:", a[idx])

Sorted Array: [1 2 3 7 9]
Indices where value > 4: (array([2, 4]),)
Values > 4: [7 9]


In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])

print("Matrix A:\n", A)
print("Vector B:", B)

Matrix A:
 [[1 2]
 [3 4]]
Vector B: [10 20]


In [ ]:
C = A + B
print("Broadcasted Addition Result:\n", C)

Broadcasted Addition Result:
 [[11 22]
 [13 24]]


In [ ]:
nums = np.array([1, 2, 3, 4, 5])
mask = nums > 3
print("Mask (nums > 3):", mask)


Mask (nums > 3): [False False False  True  True]


In [ ]:
filtered = nums[mask]
print("Filtered values:", filtered)
result = np.where(nums % 2 == 0, "Even", "Odd")
print("Even or Odd:", result)

Filtered values: [4 5]
Even or Odd: ['Odd' 'Even' 'Odd' 'Even' 'Odd']


In [ ]:
arr_orig = np.array([10, 20, 30])

arr_view = arr_orig[:]
arr_view[0] = 99
print("Original After View Change:", arr_orig)

Original After View Change: [99 20 30]


In [ ]:
arr_copy = arr_orig.copy()
arr_copy[0] = 55
print("Original After Copy Change:", arr_orig)
print("Copy:", arr_copy)

Original After Copy Change: [99 20 30]
Copy: [55 20 30]


In [ ]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
v_stack = np.vstack((x, y))
print("Vertical Stack:\n", v_stack)

Vertical Stack:
 [[1 2 3]
 [4 5 6]]


In [ ]:
h_stack = np.hstack((x, y))
print("Horizontal Stack:\n", h_stack)

# Split an array into 3 sub-arrays
z = np.arange(10)
split_arr = np.array_split(z, 3)
print("Split into 3 parts:", split_arr)

Horizontal Stack:
 [1 2 3 4 5 6]
Split into 3 parts: [array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [ ]:
rand_ints = np.random.randint(0, 100, size=(3, 3))
print("Random Integers:\n", rand_ints)

# Random values from standard normal distribution (mean=0, std=1)
rand_norm = np.random.randn(2, 4)
print("Random Normal Distribution:\n", rand_norm)

Random Integers:
 [[44 54 63]
 [72 70  9]
 [10 33 12]]
Random Normal Distribution:
 [[-0.18835252 -1.30321806  0.19456983  1.38855695]
 [ 0.96611717  2.0058658  -1.32749244 -0.99936788]]


In [ ]:
choices = np.random.choice([1, 3, 5, 7], size=5)
print("Random Choices:", choices)

# Setting a seed ensures reproducible random results
np.random.seed(42)
print("Seeded Random Number:", np.random.rand())

Random Choices: [7 7 7 5 5]
Seeded Random Number: 0.3745401188473625


In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60])
print("Original 1D Array:", arr)

# Access single elements by index
print("Element at index 0:", arr[0])
print("Element at last index:", arr[-1])

Original 1D Array: [10 20 30 40 50 60]
Element at index 0: 10
Element at last index: 60


In [ ]:
print("Slice from index 1 to 4:", arr[1:4])

# Slice with step
print("Every second element:", arr[::2])

# Reverse array
print("Reversed array:", arr[::-1])

Slice from index 1 to 4: [20 30 40]
Every second element: [10 30 50]
Reversed array: [60 50 40 30 20 10]


In [ ]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Original Matrix:\n", matrix)

# Access element at row 1, column 2
print("Element at (1,2):", matrix[1, 2])

# Get entire first row
print("First row:", matrix[0, :])

# Get entire second column
print("Second column:", matrix[:, 1])

# Slice sub-matrix (top-left 2x2 block)
print("Top-left 2x2 block:\n", matrix[:2, :2])

Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at (1,2): 6
First row: [1 2 3]
Second column: [2 5 8]
Top-left 2x2 block:
 [[1 2]
 [4 5]]


In [ ]:
arr = np.array([5, 10, 15, 20, 25, 30])

# Create a boolean mask for values > 15
mask = arr > 15
print("Boolean Mask:", mask)

# Use mask to filter elements
print("Values greater than 15:", arr[mask])

# Combine conditions
print("Even numbers > 10:", arr[(arr > 10) & (arr % 2 == 0)])

Boolean Mask: [False False False  True  True  True]
Values greater than 15: [20 25 30]
Even numbers > 10: [20 30]


In [ ]:
print("\nCorrelation between Age and Salary:")
print(df[['Age', 'Salary']].corr())

print("\nCovariance between Age and Salary:")
print(df[['Age', 'Salary']].cov())

# Frequency of values
print("\nValue counts for AgeGroup:")
print(df['AgeGroup'].value_counts())



Correlation between Age and Salary:


NameError: name 'df' is not defined

In [ ]:
print("\nCumulative sum of Salary:")
print(df['Salary'].cumsum())

print("\nCumulative max of Salary:")
print(df['Salary'].cummax())

# Rank values
print("\nRank of Salary:")
print(df['Salary'].rank())

# Quantile-based binning
print("\nQuantiles of Salary:")
print(df['Salary'].quantile([0.25, 0.5, 0.75]))


Cumulative sum of Salary:


NameError: name 'df' is not defined

In [ ]:
import pandas as pd

summary_data = {
    "Function": [
        "pd.Series()",
        "pd.DataFrame()",
        "df.head()",
        "df.tail()",
        "df.info()",
        "df.describe()",
        "df.dtypes",
        "df.loc[]",
        "df.iloc[]",
        "df['column']",
        "df[['col1','col2']]",
        "df.dropna()",
        "df.fillna()",
        "df.isnull()",
        "df.sort_values()",
        "df.groupby()",
        "df.mean(), median(), mode()",
        "df.std(), var()",
        "df.corr(), cov()",
        "df.value_counts()",
        "df.cumsum(), cummax()",
        "df.rank()",
        "df.quantile()",
        "pd.read_csv()",
        "pd.read_excel()",
        "pd.read_json()"
    ],
    "Purpose": [
        "Create a one-dimensional labeled array",
        "Create a 2D labeled data structure",
        "Display first n rows",
        "Display last n rows",
        "Summary including non-null values, types",
        "Statistical summary of numerical columns",
        "Data types of each column",
        "Label-based row/column selection",
        "Position-based row/column selection",
        "Select a single column",
        "Select multiple columns",
        "Remove rows with missing values",
        "Fill missing values",
        "Check for missing values",
        "Sort by column values",
        "Group data and apply aggregation",
        "Central tendency stats",
        "Spread or dispersion stats",
        "Relationships between columns",
        "Frequency of values",
        "Cumulative operations",
        "Ranks of data",
        "Get quantiles",
        "Read CSV file",
        "Read Excel file",
        "Read JSON file"
    ]
}

summary_df = pd.DataFrame(summary_data)
print("\nSummary of Important Pandas Functions:")
print(summary_df)


Summary of Important Pandas Functions:
                       Function                                   Purpose
0                   pd.Series()    Create a one-dimensional labeled array
1                pd.DataFrame()        Create a 2D labeled data structure
2                     df.head()                      Display first n rows
3                     df.tail()                       Display last n rows
4                     df.info()  Summary including non-null values, types
5                 df.describe()  Statistical summary of numerical columns
6                     df.dtypes                 Data types of each column
7                      df.loc[]          Label-based row/column selection
8                     df.iloc[]       Position-based row/column selection
9                  df['column']                    Select a single column
10          df[['col1','col2']]                   Select multiple columns
11                  df.dropna()           Remove rows with missing value